### ISSUE TITLE
AWS keys publicly available

### ISSUE THREAD

**Issue by TannerFilip** [itsmurugappan/MercQuizApp#1]
https://github.com/itsmurugappan/MercQuizApp/blob/master/src/main/resources/AwsCredentials.properties your access and secret key are available for anyone to use - I'm not sure what rights the user has (I didn't test them), but it's generally a bad idea to have them public.

**Comment by itsmurugappan** [comment]
i have removed it. Thanks.

**Comment by TannerFilip** [comment]
You'll probably want to revoke them if you haven't already. They'll still be available in the history
